### ISSUE TITLE
Adafruit_I2CDevice.h not found

### ISSUE THREAD

**Issue by M-Dragon4** [adafruit/Adafruit_MPL115A2#8]
- Arduino board:  Nano
- Arduino IDE version: 1.8.19

When I try to upload the example sketches getpressure or getPT to my board, the procedure fails because the compiler is unable to locate Adafruit_I2CDevice.h. Does this file exist for me to download and add to the library?

Below is the error message:
```
Arduino: 1.8.19 (Windows 10), Board: "Arduino Nano, ATmega328P"

In file included from C:\Users\Maxwell\Documents\Arduino\libraries\Adafruit_MPL115A2-2.0.0\examples\getpressure\getpressure.ino:2:0:

C:\Users\Maxwell\Documents\Arduino\libraries\Adafruit_MPL115A2-2.0.0/Adafruit_MPL115A2.h:9:10: fatal error: Adafruit_I2CDevice.h: No such file or directory

 #include <Adafruit_I2CDevice.h>

          ^~~~~~~~~~~~~~~~~~~~~~

compilation terminated.

exit status 1

Error compiling for board Arduino Nano.
```

**Comment by ladyada** [comment]
https://www.google.com/search?client=firefox-b-1-d&q=fatal+error%3A+Adafruit_I2CDevice.h%3A+No+such+file+or+directory

**Comment by M-Dragon4** [comment]
Awesome, thanks! The BusIO was what I needed.

**Comment by caternuson** [comment]
If you use Arduino's Library Manager to install, it should have taken care of the dependency:
https://github.com/adafruit/Adafruit_MPL115A2/blob/4d744533b89d07524958f49659ecc9c32bd39466/library.properties#L10

**Comment by M-Dragon4** [comment]
> If you use Arduino's Library Manager to install, it should have taken care of the dependency:
> 
> https://github.com/adafruit/Adafruit_MPL115A2/blob/4d744533b89d07524958f49659ecc9c32bd39466/library.properties#L10

I did, but unfortunately it didn't take care of it automatically, so I had to do it manually.
